<?php

return [
    'api-home' => [\App\Controller\ApiController::class, 'home'],
    'api-app-config' => [\App\Controller\ApiController::class, 'appConfig'],
    'api-operation-config' => [\App\Controller\ApiController::class, 'operationConfig'],
    'api-activity-event' => [\App\Controller\ApiController::class, 'activityEvent'],
    'api-activity-claim' => [\App\Controller\ApiController::class, 'activityClaim'],
    'api-drama' => [\App\Controller\ApiController::class, 'drama'],
    'api-me' => [\App\Controller\ApiController::class, 'me'],
    'api-order-episode' => [\App\Controller\ApiController::class, 'createEpisodeOrder'],
    'api-send-sms' => [\App\Controller\ApiController::class, 'sendSmsCode'],
    'api-login-sms' => [\App\Controller\ApiController::class, 'loginBySms'],
    'api-sms-receipt' => [\App\Controller\ApiController::class, 'smsReceipt'],
    'api-in-app-messages' => [\App\Controller\ApiController::class, 'inAppMessages'],
    'api-in-app-message-read' => [\App\Controller\ApiController::class, 'markInAppMessagesRead'],
    'api-in-app-message-archive' => [\App\Controller\ApiController::class, 'archiveInAppMessages'],
    'api-in-app-message-delete' => [\App\Controller\ApiController::class, 'deleteInAppMessages'],
    'api-player-order' => [\App\Controller\ApiController::class, 'playerOrder'],
    'api-novel-order' => [\App\Controller\ApiController::class, 'novelOrder'],
    'api-follow-drama' => [\App\Controller\ApiController::class, 'followDrama'],
    'api-watch-history' => [\App\Controller\ApiController::class, 'watchHistory'],
    'api-auto-unlock' => [\App\Controller\ApiController::class, 'autoUnlock'],
    'api-redeem-code' => [\App\Controller\ApiController::class, 'redeemCode'],
    'api-redeem-code-batch' => [\App\Controller\ApiController::class, 'redeemCodeBatch'],
    'api-promotion-event' => [\App\Controller\ApiController::class, 'promotionEvent'],
    'api-feedback-submit' => [\App\Controller\ApiController::class, 'feedbackSubmit'],
    'api-content-comments' => [\App\Controller\ApiController::class, 'contentComments'],
    'api-comment-submit' => [\App\Controller\ApiController::class, 'commentSubmit'],
    'api-ad-slots' => [\App\Controller\ApiController::class, 'adSlots'],
    'api-ad-platform-configs' => [\App\Controller\ApiController::class, 'adPlatformConfigs'],
    'api-ad-delivery-rules' => [\App\Controller\ApiController::class, 'adDeliveryRules'],
    'api-ad-event' => [\App\Controller\ApiController::class, 'adEvent'],
    'api-pay-callback' => [\App\Controller\ApiController::class, 'callback'],
];
