<?php

return [
    'home' => [\App\Controller\HomeController::class, 'index'],
    'promo' => [\App\Controller\HomeController::class, 'promo'],
    'landing-page' => [\App\Controller\HomeController::class, 'landingPage'],
    'landing-click' => [\App\Controller\HomeController::class, 'landingClick'],
    'drama' => [\App\Controller\HomeController::class, 'drama'],
    'watch' => [\App\Controller\HomeController::class, 'watch'],
    'buy-episode' => [\App\Controller\PaymentController::class, 'buyEpisode'],
    'buy-membership' => [\App\Controller\PaymentController::class, 'buyMembership'],
    'payment-result' => [\App\Controller\PaymentController::class, 'orderResult'],
    'payment-test-result' => [\App\Controller\PaymentController::class, 'paymentTestResult'],
    'pay-callback' => [\App\Controller\PaymentController::class, 'callback'],
    'jingxiu-notify' => [\App\Controller\PaymentController::class, 'jingxiuNotify'],
    'superpay-notify' => [\App\Controller\PaymentController::class, 'superpayNotify'],
    'payment-status' => [\App\Controller\PaymentController::class, 'status'],
    'center' => [\App\Controller\AccountController::class, 'center'],
    'bind' => [\App\Controller\AccountController::class, 'bind'],
    'bind-save' => [\App\Controller\AccountController::class, 'saveBind'],
    'duanju' => [\App\Controller\HomeController::class, 'duanju'],
    'novels' => [\App\Controller\HomeController::class, 'novels'],
    'novel' => [\App\Controller\HomeController::class, 'novel'],
    'novel-read' => [\App\Controller\HomeController::class, 'novelRead'],
    'juchang' => [\App\Controller\HomeController::class, 'juchang'],
    'yulan' => [\App\Controller\HomeController::class, 'yulan'],
    'zhuiju' => [\App\Controller\AccountController::class, 'zhuiju'],
    'wode' => [\App\Controller\AccountController::class, 'wode'],
    'huiyuan' => [\App\Controller\AccountController::class, 'huiyuan'],
    'denglu' => [\App\Controller\AccountController::class, 'denglu'],
    'admin' => [\App\Controller\AdminController::class, 'index'],
    'admin-logout' => [\App\Controller\AdminController::class, 'logout'],
];
